version: 2.1
jobs:
  ubuntu2004:
    docker:
      - image: ubuntu:focal-20200423
    steps:
      - run: apt-get update
      - run: apt-get install -y perl wget
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  ubuntu1804:
    docker:
      - image: ubuntu:bionic-20200403
    steps:
      - run: apt-get update
      - run: apt-get install -y perl wget
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  ubuntu1604:
    docker:
      - image: ubuntu:xenial-20200326
    steps:
      - run: apt-get update
      - run: apt-get install -y perl wget
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  ubuntu1404:
    docker:
      - image: ubuntu:trusty-20191217
    steps:
      - run: apt-get update
      - run: apt-get install -y perl wget
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  debian8:
    docker:
      - image: debian:jessie-20200514
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  debian9:
    docker:
      - image: debian:stretch-20200514
    steps:
      - run: apt-get update
      - run: apt-get install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  debian10:
    docker:
      - image: debian:buster-20200514
    steps:
      - run: apt-get update
      - run: apt-get install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  debian10_upgrade_from_repo_version:
    docker:
      - image: debian:buster-20200514
    steps:
      - run: apt-get update
      - run: apt-get install -y fastnetmon apt-utils
      - run: apt-get install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  centos6:
    docker:
      - image: centos:centos6.9
    steps:
      - run: yum install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  centos7:
    docker:
      - image: centos:centos7.8.2003
    steps:
      - run: yum install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
  centos8:
    docker:
      - image: centos:centos8.1.1911
    steps:
      - run: yum install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
workflows:
  version: 2
  all_distros:
    jobs:
      - debian8
      - debian9
      - debian10
      - debian10_upgrade_from_repo_version
      - ubuntu1404
      - ubuntu1604
      - ubuntu1804
      - ubuntu2004
      - centos6
      - centos7
      - centos8
