version: 2.1
jobs:
  ubuntu2004:
    docker:
      - image: ubuntu:focal
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu2004_ci:
    docker:
      - image: ubuntu:focal
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition -developer_version
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1804:
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1804_ci:
    docker:
      - image: ubuntu:bionic
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition -developer_version
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1604:
    docker:
      - image: ubuntu:xenial
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1604_ci:
    docker:
      - image: ubuntu:xenial
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition -developer_version
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1404:
    docker:
      - image: ubuntu:trusty
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget --no-check-certificate  https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1404_ci:
    docker:
      - image: ubuntu:trusty
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget --no-check-certificate https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition -developer_version
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian8:
    docker:
      - image: debian:jessie
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget --no-check-certificate https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian9:
    docker:
      - image: debian:stretch
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian9_ci:
    docker:
      - image: debian:stretch
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition -developer_version
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian10:
    docker:
      - image: debian:buster
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian10_ci:
    docker:
      - image: debian:buster
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition -developer_version
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian10_upgrade_from_repo_version:
    docker:
      - image: debian:buster
    steps:
      - run: apt-get update
      - run: apt-get install -y fastnetmon apt-utils
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: dpkg -l |grep fastnetmon
  centos6:
    docker:
      - image: centos:centos6
    steps:
      - run: sed -i '/mirrorlist/d' /etc/yum.repos.d/CentOS-Base.repo
      - run: sed -i 's/#baseurl/baseurl/' /etc/yum.repos.d/CentOS-Base.repo
      - run: sed -i 's/mirror.centos.org/vault.centos.org/' /etc/yum.repos.d/CentOS-Base.repo
      - run: yum install -y wget
      - run: wget --no-check-certificate https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos7:
    docker:
      - image: centos:centos7
    steps:
      - run: yum install -y wget
      - run: wget --no-check-certificate https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos7_ci:
    docker:
      - image: centos:centos7
    steps:
      - run: yum install -y wget
      - run: wget --no-check-certificate https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition -developer_version
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos8:
    docker:
      - image: almalinux:8
    steps:
      - run: yum install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos8_ci:
    docker:
      - image: almalinux:8
    steps:
      - run: yum install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition -developer_version
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check

workflows:
  version: 2
  all_distros:
    jobs:
      - debian8
      - debian9
      - debian9_ci
      - debian10
      - debian10_ci
      - debian10_upgrade_from_repo_version
      - ubuntu1404
      - ubuntu1404_ci
      - ubuntu1604
      - ubuntu1604_ci
      - ubuntu1804
      - ubuntu1804_ci
      - ubuntu2004
      - ubuntu2004_ci
      - centos6
      - centos7
      - centos7_ci
      - centos8
      - centos8_ci
