version: 2.1
jobs:
  build_ubuntu:
    docker:
      - image: << parameters.docker_image >>
    parameters:
      docker_image:
        type: string
      wget_arguments:
        type: string
        default: ""
      installer_arguments:
        type: string
        default: ""
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget << parameters.wget_arguments >> https://install.fastnetmon.com/installer?random-argument-to-disable-caching-$CIRCLE_WORKFLOW_JOB_ID -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition << parameters.installer_arguments >>
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: /opt/fastnetmon/fastnetmon_client --help
  build_debian:
    docker:
      - image: << parameters.docker_image >>
    parameters:
      docker_image:
        type: string
      wget_arguments:
        type: string
        default: ""
      installer_arguments:
        type: string
        default: ""
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget << parameters.wget_arguments >> https://install.fastnetmon.com/installer?random-argument-to-disable-caching-$CIRCLE_WORKFLOW_JOB_ID -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition << parameters.installer_arguments >>
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: /opt/fastnetmon/fastnetmon_client --help
  build_debian_upstream:
    docker:
      - image: << parameters.docker_image >>
    parameters:
      docker_image:
        type: string
    steps:
      - run: apt-get update
      - run: apt-get install -y fastnetmon
      - run: ldd /usr/sbin/fastnetmon
      - run: ldd /usr/bin/fastnetmon_client
      - run: /usr/sbin/fastnetmon --configuration_check
      - run: /usr/bin/fastnetmon_client --help

  debian10_upgrade_from_repo_version:
    docker:
      - image: debian:buster
    steps:
      - run: apt-get update
      - run: apt-get install -y fastnetmon apt-utils
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer?random-argument-to-disable-caching-$CIRCLE_WORKFLOW_JOB_ID -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: /opt/fastnetmon/fastnetmon_client --help
      - run: dpkg -l |grep fastnetmon
  build_centos:
    docker:
      - image: << parameters.docker_image >>
    parameters:
      docker_image:
        type: string
      wget_arguments:
        type: string
        default: ""
      installer_arguments:
        type: string
        default: ""
    steps:
      - run: yum install -y wget
      - run: wget << parameters.wget_arguments >> https://install.fastnetmon.com/installer?random-argument-to-disable-caching-$CIRCLE_WORKFLOW_JOB_ID -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition << parameters.installer_arguments >>
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: /opt/fastnetmon/fastnetmon_client --help
  centos6:
    docker:
      - image: centos:centos6
    steps:
      - run: sed -i '/mirrorlist/d' /etc/yum.repos.d/CentOS-Base.repo
      - run: sed -i 's/#baseurl/baseurl/' /etc/yum.repos.d/CentOS-Base.repo
      - run: sed -i 's/mirror.centos.org/vault.centos.org/' /etc/yum.repos.d/CentOS-Base.repo
      - run: yum install -y wget
      - run: wget --no-check-certificate https://install.fastnetmon.com/installer?random-argument-to-disable-caching-$CIRCLE_WORKFLOW_JOB_ID -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: /opt/fastnetmon/fastnetmon_client --help
  build_fedora:
    docker:
      - image: << parameters.docker_image >>
    parameters:
      docker_image:
        type: string
    steps:
      - run: dnf install -y fastnetmon
      - run: ldd /usr/sbin/fastnetmon
      - run: ldd /usr/bin/fastnetmon_client
      - run: ldd /usr/bin/fastnetmon_api_client
      - run: /usr/sbin/fastnetmon --configuration_check
      - run: /usr/bin/fastnetmon_client --help

workflows:
  version: 2
  all_distros_nightly:
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - debian10_upgrade_from_repo_version
      - build_debian:
          name: "Debian 8"
          docker_image: debian:jessie
          wget_arguments: "--no-check-certificate"
      - build_debian:
          name: "Debian 9"
          docker_image: debian:stretch
      - build_debian:
          name: "Debian 10"
          docker_image: debian:buster
      - build_debian:
          name: "Debian 11"
          docker_image: debian:bullseye
      - build_debian:
          name: "Debian 9 dev"
          docker_image: debian:stretch
          installer_arguments: "-developer_version"
      - build_debian:
          name: "Debian 10 dev"
          docker_image: debian:buster
          installer_arguments: "-developer_version"
      - build_debian_upstream:
          name: "Debian Sid Upstream"
          docker_image: debian:sid
      - build_debian:
          name: "Debian 11 dev"
          docker_image: debian:bullseye
          installer_arguments: "-developer_version"
      - build_ubuntu:
          name: "Ubuntu 14.04"
          docker_image: ubuntu:trusty
          wget_arguments: "--no-check-certificate"
      - build_ubuntu:
          name: "Ubuntu 16.04"
          docker_image: ubuntu:xenial
      - build_ubuntu:
          name: "Ubuntu 18.04"
          docker_image: ubuntu:bionic
      - build_ubuntu:
          name: "Ubuntu 20.04"
          docker_image: ubuntu:focal
      - build_ubuntu:
          name: "Ubuntu 14.04 dev"
          docker_image: ubuntu:trusty
          wget_arguments: "--no-check-certificate"
          installer_arguments: "-developer_version"
      - build_ubuntu:
          name: "Ubuntu 16.04 dev"
          docker_image: ubuntu:xenial
          installer_arguments: "-developer_version"
      - build_ubuntu:
          name: "Ubuntu 18.04 dev"
          docker_image: ubuntu:bionic
          installer_arguments: "-developer_version"
      - build_ubuntu:
          name: "Ubuntu 20.04 dev"
          docker_image: ubuntu:focal
          installer_arguments: "-developer_version"
      - build_ubuntu:
          name: "Ubuntu 22.04 dev"
          docker_image: ubuntu:jammy
          installer_arguments: "-developer_version"
      - centos6
      - build_centos:
          name: "CentOS 7"
          docker_image: centos:centos7
          wget_arguments: "--no-check-certificate"
      - build_centos:
          name: "CentOS 8"
          docker_image: almalinux:8
      - build_centos:
          name: "CentOS 7 dev"
          docker_image: centos:centos7
          wget_arguments: "--no-check-certificate"
          installer_arguments: "-developer_version"
      - build_centos:
          name: "CentOS 8 dev"
          docker_image: almalinux:8
          installer_arguments: "-developer_version"
      - build_centos:
          name: "CentOS 9 dev"
          docker_image: almalinux:9
          installer_arguments: "-developer_version"
      - build_fedora:
          name: "Fedora Rawhide upstream"
          docker_image: fedora:rawhide
  all_distros:
    jobs:
      - debian10_upgrade_from_repo_version
      - build_debian:
          name: "Debian 8"
          docker_image: debian:jessie
          wget_arguments: "--no-check-certificate"
      - build_debian:
          name: "Debian 9"
          docker_image: debian:stretch
      - build_debian:
          name: "Debian 10"
          docker_image: debian:buster
      - build_debian:
          name: "Debian 11"
          docker_image: debian:bullseye
      - build_debian:
          name: "Debian 9 dev"
          docker_image: debian:stretch
          installer_arguments: "-developer_version"
      - build_debian:
          name: "Debian 10 dev"
          docker_image: debian:buster
          installer_arguments: "-developer_version"
      - build_debian:
          name: "Debian 11 dev"
          docker_image: debian:bullseye
          installer_arguments: "-developer_version"
      - build_debian_upstream:
          name: "Debian Sid Upstream"
          docker_image: debian:sid
      - build_ubuntu:
          name: "Ubuntu 14.04"
          docker_image: ubuntu:trusty
          wget_arguments: "--no-check-certificate"
      - build_ubuntu:
          name: "Ubuntu 16.04"
          docker_image: ubuntu:xenial
      - build_ubuntu:
          name: "Ubuntu 18.04"
          docker_image: ubuntu:bionic
      - build_ubuntu:
          name: "Ubuntu 20.04"
          docker_image: ubuntu:focal
      - build_ubuntu:
          name: "Ubuntu 22.04"
          docker_image: ubuntu:jammy
      - build_ubuntu:
          name: "Ubuntu 14.04 dev"
          docker_image: ubuntu:trusty
          wget_arguments: "--no-check-certificate"
          installer_arguments: "-developer_version"
      - build_ubuntu:
          name: "Ubuntu 16.04 dev"
          docker_image: ubuntu:xenial
          installer_arguments: "-developer_version"
      - build_ubuntu:
          name: "Ubuntu 18.04 dev"
          docker_image: ubuntu:bionic
          installer_arguments: "-developer_version"
      - build_ubuntu:
          name: "Ubuntu 20.04 dev"
          docker_image: ubuntu:focal
          installer_arguments: "-developer_version"
      - build_ubuntu:
          name: "Ubuntu 22.04 dev"
          docker_image: ubuntu:jammy
          installer_arguments: "-developer_version"
      - centos6
      - build_centos:
          name: "CentOS 7"
          docker_image: centos:centos7
          wget_arguments: "--no-check-certificate"
      - build_centos:
          name: "CentOS 8"
          docker_image: almalinux:8
      - build_centos:
          name: "CentOS 7 dev"
          docker_image: centos:centos7
          wget_arguments: "--no-check-certificate"
          installer_arguments: "-developer_version"
      - build_centos:
          name: "CentOS 8 dev"
          docker_image: almalinux:8
          installer_arguments: "-developer_version"
      - build_centos:
          name: "CentOS 9 dev"
          docker_image: almalinux:9
          installer_arguments: "-developer_version"
      - build_fedora:
          name: "Fedora Rawhide upstream"
          docker_image: fedora:rawhide

