version: 2.1
jobs:
  ubuntu2004:
    docker:
      - image: ubuntu:focal-20200423
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu2004_ci:
    docker:
      - image: ubuntu:focal-20200423
    steps:
      - run: apt-get update
      - run: apt-get install -y perl wget
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1804:
    docker:
      - image: ubuntu:bionic-20200403
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1804_ci:
    docker:
      - image: ubuntu:bionic-20200403
    steps:
      - run: apt-get update
      - run: apt-get install -y perl wget
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1604:
    docker:
      - image: ubuntu:xenial-20200326
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1604_ci:
    docker:
      - image: ubuntu:xenial-20200326
    steps:
      - run: apt-get update
      - run: apt-get install -y perl wget
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1404:
    docker:
      - image: ubuntu:trusty-20191217
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  ubuntu1404_ci:
    docker:
      - image: ubuntu:trusty-20191217
    steps:
      - run: apt-get update
      - run: apt-get install -y perl wget
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian8:
    docker:
      - image: debian:jessie-20200514
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian8_ci:
    docker:
      - image: debian:jessie-20200514
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian9:
    docker:
      - image: debian:stretch-20200514
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian9_ci:
    docker:
      - image: debian:stretch-20200514
    steps:
      - run: apt-get update
      - run: apt-get install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian10:
    docker:
      - image: debian:buster-20200514
    steps:
      - run: apt-get update
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian10_ci:
    docker:
      - image: debian:buster-20200514
    steps:
      - run: apt-get update
      - run: apt-get install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  debian10_upgrade_from_repo_version:
    docker:
      - image: debian:buster-20200514
    steps:
      - run: apt-get update
      - run: apt-get install -y fastnetmon apt-utils
      - run: apt-get install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
      - run: dpkg -l |grep fastnetmon
  centos6:
    docker:
      - image: centos:centos6.9
    steps:
      - run: sed -i '/mirrorlist/d' /etc/yum.repos.d/CentOS-Base.repo
      - run: sed -i 's/#baseurl/baseurl/' /etc/yum.repos.d/CentOS-Base.repo
      - run: sed -i 's/mirror.centos.org/vault.centos.org/' /etc/yum.repos.d/CentOS-Base.repo
      - run: yum install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos6_ci:
    docker:
      - image: centos:centos6.9
    steps:
      - run: sed -i '/mirrorlist/d' /etc/yum.repos.d/CentOS-Base.repo
      - run: sed -i 's/#baseurl/baseurl/' /etc/yum.repos.d/CentOS-Base.repo
      - run: sed -i 's/mirror.centos.org/vault.centos.org/' /etc/yum.repos.d/CentOS-Base.repo
      - run: yum install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos7:
    docker:
      - image: centos:centos7.8.2003
    steps:
      - run: yum install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos7_ci:
    docker:
      - image: centos:centos7.8.2003
    steps:
      - run: yum install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos8:
    docker:
      - image: centos:centos8.1.1911
    steps:
      - run: yum install -y wget
      - run: wget https://install.fastnetmon.com/installer -Oinstaller
      - run: chmod +x installer
      - run: ./installer -install_community_edition
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check
  centos8_ci:
    docker:
      - image: centos:centos8.1.1911
    steps:
      - run: yum install -y wget perl
      - run: wget https://raw.githubusercontent.com/pavel-odintsov/fastnetmon/master/src/fastnetmon_install.pl -Ofastnetmon_install.pl
      - run: perl fastnetmon_install.pl --install-ci-packages
      - store_artifacts:
          path: /tmp/fastnetmon_install.log
      - run: ldd /opt/fastnetmon/fastnetmon
      - run: ldd /opt/fastnetmon/fastnetmon_client
      - run: ldd /opt/fastnetmon/fastnetmon_api_client
      - run: /opt/fastnetmon/fastnetmon --configuration_check

workflows:
  version: 2
  all_distros:
    jobs:
      - debian8
      - debian8_ci
      - debian9
      - debian9_ci
      - debian10
      - debian10_ci
      - debian10_upgrade_from_repo_version
      - ubuntu1404
      - ubuntu1404_ci
      - ubuntu1604
      - ubuntu1604_ci
      - ubuntu1804
      - ubuntu1804_ci
      - ubuntu2004
      - ubuntu2004_ci
      - centos6
      - centos6_ci
      - centos7
      - centos7_ci
      - centos8
      - centos8_ci
